-- backend/create_audit_log_schema.sql
-- Run this in Supabase SQL Editor to create the job_audit_logs table

CREATE TABLE IF NOT EXISTS public.job_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    field_name TEXT NOT NULL, -- 'status' or 'price'
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.job_audit_logs ENABLE ROW LEVEL SECURITY;

-- Policies are not needed as the FastAPI backend uses a Service Role key to access Supabase,
-- thus bypassing RLS entirely. The backend manages authorization natively itself.
